services:
  postgres:
    image: postgres:15.1
    container_name: postgres_database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./databases/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=courseDb

  pg:
    container_name: pgAdmin
    depends_on:
      - postgres
    image: dpage/pgadmin4:6.17
    volumes:
      - ./databases/pgadmin:/var/lib/pgadmin
    ports:
      - "9090:80"
    environment:
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_DEFAULT_EMAIL=example@example.com
    restart: always

  mysql:
    image: mysql:8.0.33
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=studentDb
    volumes:
      - ./databases/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:5.2.0-apache
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "9091:80"
    depends_on:
      - mysql

volumes:
  databases:
    driver: local